name: release-crates
on:
  push:
    tags:
      - "v*"

jobs:
  publish-crates:
    permissions:
      contents: read
      id-token: write
    uses: csaf-rs/shared-workflows/.github/workflows/cargo-publish.yml@4828cd545465d4faade7eb410621ad7d8954f0dc # v1.9.0
    with:
      environment: release
