name: release-crates
on:
  push:
    tags:
      - "v*"

jobs:
  publish-crates:
    permissions:
      contents: read
      id-token: write
    uses: csaf-rs/shared-workflows/.github/workflows/cargo-publish.yml@c2f5f2066f1d96c12c1e33a8dea1fceb5eb37366 # v1.12.0
    with:
      environment: release
