name: release-crates
on:
  push:
    tags:
      - "v*"

jobs:
  publish-crates:
    permissions:
      contents: read
      id-token: write
    uses: csaf-rs/shared-workflows/.github/workflows/cargo-publish.yml@a026baa029a5f7d7b1dfca973cdcd0c940e545dc # v1.11.0
    with:
      environment: release
